name: 'Copilot Setup Steps'

on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get Package Manager
        uses: helloextend/gha-reusable-workflows/.github/actions/get-package-manager@main
        id: getPackageManager

      - name: Enable Corepack
        run: npm i -g --force corepack && corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: ${{ steps.getPackageManager.outputs.packageManager }}

      - name: Setup NPM
        uses: helloextend/gha-reusable-workflows/.github/actions/npm-login@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install node-gyp globally
        run: npm install -g node-gyp

      - name: Install Dependencies
        run: ${{ steps.getPackageManager.outputs.packageManager }} install --frozen-lockfile
